/**
 * Atlas reframe WP1 — project-page model tests. Two layers: targeted literal
 * graphs pin the pure branches (brief freshness, blocked count, empty), and a
 * contract suite reads real LEARN graphs captured from the nimbus simulation
 * vault (fixtures/learn-*.json, generated by projectAtlas) and asserts the page
 * reads correctly for nimbus-frontend + nimbus-backend. The builder lives in the
 * web project, which cannot import the node-side core; the committed fixtures
 * carry the real vault's ground truth instead.
 */
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import type { AtlasGraph, AtlasNode } from '../../../../shared/types'
import { buildProjectPage } from './project-page'

function loadLearn(project: string): AtlasGraph {
  const path = resolve(import.meta.dirname, `fixtures/learn-${project}.json`)
  return JSON.parse(readFileSync(path, 'utf8')) as AtlasGraph
}

// ── literal-graph unit branches ──────────────────────────────────────────────

const note = (over: Partial<AtlasNode>): AtlasNode => ({
  id: over.id ?? 'note:alpha/streaming/x',
  type: 'note',
  label: over.label ?? 'x',
  project: 'alpha',
  topic: 'streaming',
  x: 0,
  y: 0,
  ...over,
})

const handoff = (over: Partial<AtlasNode>): AtlasNode => ({
  id: over.id ?? 'handoff:alpha/h',
  type: 'handoff',
  label: over.label ?? 'h',
  project: 'alpha',
  topic: 'handoffs',
  x: 0,
  y: 0,
  from: 'beta',
  to: 'alpha',
  status: 'open',
  kind: 'delivery',
  ...over,
})

function graphOf(nodes: AtlasNode[]): AtlasGraph {
  const topics = new Map<string, string[]>()
  for (const n of nodes) {
    const t = n.topic || '(project root)'
    topics.set(t, [...(topics.get(t) ?? []), n.id])
  }
  return {
    level: 'learn',
    scope: { project: 'alpha' },
    nodes: [
      { id: 'project:alpha', type: 'project', label: 'alpha', project: 'alpha', x: 0, y: 0, openCount: 0, noteCount: nodes.length },
      ...nodes,
    ],
    edges: [],
    clusters: [
      {
        project: 'alpha',
        topics: [...topics.entries()].map(([name, ids]) => ({
          name,
          nodeIds: ids,
          singleChild: ids.length === 1,
        })),
      },
    ],
    cyclic: false,
  }
}

describe('buildProjectPage (units)', () => {
  it('groups notes into topic sections, newest topic first, notes newest-first', () => {
    const g = graphOf([
      note({ id: 'note:alpha/streaming/a', label: 'a', topic: 'streaming', date: '2026-07-01' }),
      note({ id: 'note:alpha/streaming/b', label: 'b', topic: 'streaming', date: '2026-07-05' }),
      note({ id: 'note:alpha/agent-config/c', label: 'c', topic: 'agent-config', date: '2026-07-09' }),
    ])
    const page = buildProjectPage(g, '2026-07-10')
    expect(page.topics.map((t) => t.topic)).toEqual(['agent-config', 'streaming'])
    const streaming = page.topics.find((t) => t.topic === 'streaming')
    expect(streaming?.count).toBe(2)
    expect(streaming?.newestDate).toBe('2026-07-05')
    expect(streaming?.notes.map((n) => n.name)).toEqual(['b', 'a']) // newest first
    expect(page.header.noteCount).toBe(3)
  })

  it('humanizes titles and carries type/excerpt/date onto note cards', () => {
    const g = graphOf([
      note({
        id: 'note:alpha/streaming/2026-07-05-error-handling',
        label: '2026-07-05-error-handling',
        topic: 'streaming',
        date: '2026-07-05',
        noteType: 'finding',
        summary: 'SSE retries need a backoff.',
        path: 'projects/alpha/streaming/2026-07-05-error-handling.md',
      }),
    ])
    const card = buildProjectPage(g, '2026-07-10').topics[0]?.notes[0]
    expect(card?.title).toBe('Error Handling')
    expect(card?.noteType).toBe('finding')
    expect(card?.excerpt).toBe('SSE retries need a backoff.')
    expect(card?.date).toBe('2026-07-05')
    expect(card?.path).toBe('projects/alpha/streaming/2026-07-05-error-handling.md')
  })

  it('brief freshness: none without a brief, fresh/stale from the brief note', () => {
    expect(buildProjectPage(graphOf([note({})]), '2026-07-10').header.briefFreshness).toBe('none')

    const fresh = graphOf([
      note({ id: 'note:alpha/brief', label: 'start-here', noteType: 'brief', stale: false, path: 'projects/alpha/start-here.md' }),
    ])
    expect(buildProjectPage(fresh).header).toMatchObject({
      briefFreshness: 'fresh',
      briefPath: 'projects/alpha/start-here.md',
    })

    const stale = graphOf([note({ id: 'note:alpha/b', label: 'x', noteType: 'brief', stale: true })])
    expect(buildProjectPage(stale).header.briefFreshness).toBe('stale')
  })

  it('attention.blocked counts open/accepted request handoffs only', () => {
    const g = graphOf([
      handoff({ id: 'handoff:alpha/req', label: 'req', kind: 'request', status: 'open' }),
      handoff({ id: 'handoff:alpha/acc', label: 'acc', kind: 'request', status: 'accepted' }),
      handoff({ id: 'handoff:alpha/del', label: 'del', kind: 'delivery', status: 'open' }),
      handoff({ id: 'handoff:alpha/done', label: 'done', kind: 'request', status: 'consumed' }),
    ])
    expect(buildProjectPage(g, '2026-07-10').attention.blocked).toBe(2)
  })

  it('reconstructs board handoff cards (age from date) for HandoffCardView', () => {
    const g = graphOf([
      handoff({
        id: 'handoff:alpha/h',
        label: '2026-07-08-handoff-beta',
        from: 'beta',
        to: 'alpha',
        status: 'open',
        kind: 'delivery',
        date: '2026-07-08',
        summary: 'Wire the retry banner.',
        path: 'projects/alpha/handoffs/2026-07-08-handoff-beta.md',
      }),
    ])
    const card = buildProjectPage(g, '2026-07-10').handoffs[0]
    expect(card).toMatchObject({
      id: '2026-07-08-handoff-beta',
      from: 'beta',
      to: 'alpha',
      objective: 'Wire the retry banner.',
      status: 'open',
      ageDays: 2,
      path: 'projects/alpha/handoffs/2026-07-08-handoff-beta.md',
      readingOrder: [],
    })
  })

  it('empty cluster degrades to zero counts, no topics, no handoffs', () => {
    const page = buildProjectPage(graphOf([]), '2026-07-10')
    expect(page.header.noteCount).toBe(0)
    expect(page.topics).toHaveLength(0)
    expect(page.handoffs).toHaveLength(0)
    expect(page.header.lastActivity).toBeNull()
  })
})

// ── contract suite against the real nimbus simulation vault (captured) ──────

describe('buildProjectPage (nimbus vault)', () => {
  const learnFrontend = loadLearn('nimbus-frontend')
  const learnBackend = loadLearn('nimbus-backend')

  it('nimbus-frontend: header, streaming + agent-config topics, humanized titles', () => {
    const page = buildProjectPage(learnFrontend, '2026-07-10')
    expect(page.header.project).toBe('nimbus-frontend')
    expect(page.header.noteCount).toBeGreaterThanOrEqual(2)
    const topicNames = page.topics.map((t) => t.topic)
    expect(topicNames).toContain('streaming')
    expect(topicNames).toContain('agent-config')
    const streaming = page.topics.find((t) => t.topic === 'streaming')
    expect(streaming?.notes.some((n) => n.title === 'Streaming Ui')).toBe(true)
    // every note card is Reader-openable and titled (never a raw filename)
    for (const t of page.topics) {
      for (const n of t.notes) {
        expect(n.path.endsWith('.md')).toBe(true)
        expect(n.title.length).toBeGreaterThan(0)
      }
    }
  })

  it('nimbus-frontend: flows-with backend, handoff cards, attention mirrors open', () => {
    const page = buildProjectPage(learnFrontend, '2026-07-10')
    const flowNames = [...page.flows.inbound, ...page.flows.outbound].map((c) => c.project)
    expect(flowNames).toContain('nimbus-backend')
    expect(page.handoffs.length).toBeGreaterThanOrEqual(1)
    for (const h of page.handoffs) {
      expect(h.from.length).toBeGreaterThan(0)
      expect(h.to.length).toBeGreaterThan(0)
    }
    expect(page.attention.open).toBe(page.header.openCount)
  })

  it('nimbus-backend: topics newest-first, handoffs never leak into topic sections', () => {
    const page = buildProjectPage(learnBackend, '2026-07-10')
    expect(page.topics.map((t) => t.topic)).not.toContain('handoffs')
    // recency-ordered reading flow: newest topic first
    for (let i = 1; i < page.topics.length; i++) {
      expect(
        (page.topics[i - 1]?.newestDate ?? '') >= (page.topics[i]?.newestDate ?? ''),
      ).toBe(true)
    }
    expect(page.handoffs.length).toBeGreaterThanOrEqual(1)
  })

  it('is deterministic across builds', () => {
    expect(buildProjectPage(learnBackend, '2026-07-10')).toEqual(
      buildProjectPage(learnBackend, '2026-07-10'),
    )
  })
})
